- NVIDIA/CUDADriver.munki.recipe
- NVIDIA/CUDADriverURLProvider.py
A few handy improvements to the CUDA recipe. I started just with the intention of adding the input variable but then decided it's useful to have the recipe automatically handle the version constraints, so now it keeps attempting a lower version in the predicate object until it returns False.
Not sure whether it would be also handy to set a `maximum_os_version` as some protective measure - but I think in most cases admins when keeping this recipe in rotation will end up having the newer drivers available anyway. Also, I don't think one can assume that a driver for 10.10 _won't_ work on 10.11 in all cases, for example.
Not attached to the name `MAJOR_OS_VERSION` for the Input variable, if you have any ideas.
> Improved OS version metadata in CUDADriver.munki

- dockutil/dockutil.pkg.recipe
The package isn't making dockutil executable.
> Make dockutil executable

- LoginScriptPlugin/LoginScriptPlugin.munki.recipe
Updated LoginScriptPlugin munki recipe to remove postinstall script that killed loginwindow.app as it caused issues when installed in logged out state via Munki
> Updated LoginScriptPlugin munki recipe

- VMware/VMwareTools.munki.recipe
- VMware/VMwareToolsURLProvider.py
This is definitely needed since the update URL's are all http.
> VMwareTools.munki - Add CodeSignatureVerifier

- Cristallight/iBarcoder.download.recipe
and end of check phase. Hope it's OK I bumped the version requirement
to most recent autopkg, since only higher than .3.1 had codesigverif in
core.
> add codesigverif to iBarcoder

- dockutil/dockutil.download.recipe
This will get only the latest release instead of the modified binary in the GitHub project.
> Download latest release instead of binary

- NVIDIA/CUDADriver.download.recipe
Just noticed CUDA 8 had been out for a while but this recipe was still retrieving a 7.x version. Bumping `MAJOR_OS_VERSION` to either 10.11 or 10.12 will retrieve the latest version - figured I would put it to the latest since currently that doesn't "skip" any supported versions.
> Update MAJOR_OS_VERSION in CUDADriver.munki to 10.12

- VMware/VMwareTools.munki.recipe
As of 8.5.4, Fusion now ships two different darwin tools ISOs: `darwin.iso` and `darwinPre15.iso`. `darwin.iso` now has a minimum OS of 10.11 set in its pkg distribution file. So this just sets the `minimum_os_version` to match.
Not sure how much of a demand there is to keep older VMs up to date, but perhaps that would call for a duplicate recipe like `VMwareToolsYosemite.munki` (or something) which has a `maximum_os_version` of `10.10.5`. Figured the first part is the lower-hanging fruit and would affect the most users.
> Require 10.11 for VMwareTools.munki

- NVIDIA/CUDADriver.download.recipe
This one just adds pkg signature validation to the installer package for the CUDA driver.
> Add pkg signature validation to CUDADriver.download

- Extensis/UniversalTypeClient6.munki.recipe
The removal tool URL changed, support pointed me to the new one and updated their wiki article.
> Update UTC6 removal tool URL

- NVIDIA/CUDADriver.download.recipe
This seems to have changed about a month ago.
> New signature authority on CUDA driver

- Code42/CrashPlan.download.recipe
> Updated authority name for CrashPlan

- dockutil/dockutil.munki.recipe
According to the read me: https://github.com/kcrawford/dockutil
> Compatible with Mac OS X 10.9.x thru 10.13 (use 1.x version for older OSes)
> Set minimum OS version for dockutil to 10.9

- Cristallight/iBarcoder.download.recipe
Because variables can be overridden, it's a good idea to make sure that the recipe will still work even if a non-default variables used. One issue that would prevent recipes from running is using a `NAME` variable in paths that should be hard-coded (e.g. `/Applications/Foo.app`).
This PR removes the `NAME` variable from all file paths and replaces it with the actual app name, which should make the recipe more resilient for overrides.
> Remove NAME variable from app paths

- Extensis/FindResource.py
- Extensis/ModeChanger.py
- GrandPerspective/SourceForgeURLProvider.py
- LoginScriptPlugin/LoginScriptPluginUninstallCreator.py
- NVIDIA/CUDADriverURLProvider.py
- Oracle/VirtualBoxURLProvider.py
- PredicateInstaller/TimestampVersioner.py
- TrueCrypt/TrueCryptURLProvider.py
- VMware/ImageConverter.py
- VMware/VMwareToolsURLProvider.py
In order to make your processors more compatible with AutoPkg running in Python 3, I've applied a few adjustments suggested by `python-modernize`, `pylint --py3k`, and `pylint` in general.
More adjustments may need to be made manually later (including `urllib2.HTTPRedirectHandler`), but this should catch the low-hanging fruit right now.
> Basic python3 compatibility

- ClamXav/ClamXav.download.recipe
The description says "imports into Munki," but the recipe does not include a MunkiImporter process.
> Adjust description of download recipe

- TrueCrypt/TrueCrypt.munki.recipe
From http://truecrypt.sourceforge.net:
> WARNING: Using TrueCrypt is not secure as it may contain unfixed security issues
> Deprecate TrueCrypt recipe

- Hightail/HightailDesktopApp.munki.recipe
The correct argument name for [URLDownloader](https://github.com/autopkg/autopkg/wiki/Processor-URLDownloader) is `filename`.
> Adjust URLDownloader argument

- NVIDIA/CUDADriver.download.recipe
Nvidia CUDA 10.2 (toolkit and driver) was the last release to support macOS. Details:
- https://docs.nvidia.com/cuda/archive/10.2/cuda-toolkit-release-notes/index.html#title-new-features
- https://mjtsai.com/blog/2019/11/25/nvidia-drops-cuda-support-for-macos/
- https://gizmodo.com/apple-and-nvidia-are-over-1840015246
Related: https://github.com/autopkg/novaksam-recipes/pull/68, https://github.com/autopkg/jps3-recipes/pull/91
> Deprecate Nvidia CUDA recipes

- Code42/CrashPlan.download.recipe
- updated Code42 download URL
- added Versioner processor (unpacks package files and reads version from Info.plist, purges temp directory when finished)
- updated `%NAME%` (left recipe identifier unchanged to not break recipe overrides, but it should probably get updated at some point to reflect the current app name)
> updated Code42 download URL, added Versioner check

- Oracle/VirtualBoxURLProvider.py
The [MD5SUMS](https://download.virtualbox.org/virtualbox/6.1.20/MD5SUMS) file contains extraneous entries ending in `.delete`:
```
d41d8cd98f00b204e9800998ecf8427e *Oracle_VM_VirtualBox_Extension_Pack-6.1.20-143848.vbox-extpack.delete
d41d8cd98f00b204e9800998ecf8427e *Oracle_VM_VirtualBox_Extension_Pack-6.1.20-143869.vbox-extpack.delete
66e34c2689f23102fb633778504057b4 *Oracle_VM_VirtualBox_Extension_Pack-6.1.20-143896.vbox-extpack
...
```
**Current invalid behaviour**
Oracle_VM_VirtualBox_Extension_Pack-6.1.20-143848.vbox-extpack (this file [does not exist](https://download.virtualbox.org/virtualbox/6.1.20/Oracle_VM_VirtualBox_Extension_Pack-6.1.20-143848.vbox-extpack) and it ends with .delete).
**Expected behaviour**
Oracle_VM_VirtualBox_Extension_Pack-6.1.20-143896.vbox-extpack (this …
> Update VirtualBoxURLProvider.py to workaround extraneous entries in MD5SUMS.

- LoginScriptPlugin/LoginScriptPluginUninstallCreator.py
- PredicateInstaller/TimestampVersioner.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
> Update Python path in processors to reflect changes in macOS 12.3+

- Code42/CrashPlan.download.recipe
These CrashPlan recipes no longer work, and are now redundant with Code42 recipes in other repos. This PR deprecates the CrashPlan recipes and points users to the apizz-recipes repo for a possible replacement.
> Deprecate CrashPlan recipes

- Mekentosj/Papers2.download.recipe
This PR adjusts the download method for the latest version of the Papers app. It also adds code signature verification for the app, and adds an ARCH input variable that can be used to specify the desired architecture.
Verbose recipe run with default (Intel) architecture:
```
% autopkg run -vvq 'Mekentosj/Papers2.download.recipe'
Processing Mekentosj/Papers2.download.recipe...
WARNING: Mekentosj/Papers2.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '(Papers_Setup_[\\d\\.]+-x64.dmg)',
'url': 'https://update.readcube.com/desktop/updates/latest-mac.yml'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (match): …
```
> Fix Papers recipes, add code signature verification, and add ARCH input variable

- 4D/4D.download.recipe
- Extensis/PortfolioClient10.munki.recipe
- Extensis/PortfolioClient11.munki.recipe
- Extensis/UniversalTypeClient3.munki.recipe
- MOOSProjectViewer/MOOSProjectViewer.download.recipe
- NIH-RSB/ImageJ.munki.recipe
It's important to use HTTPS for downloading software whenever possible in order to avoid the possibility of person-in-the-middle attacks (like the one that affected the Sparkle update framework [back in 2016](https://vulnsec.com/2016/osx-apps-vulnerabilities/)).
For this pull request, I detected and changed to HTTPS URLs automatically using my [HTTPS Spotter](https://www.elliotjordan.com/posts/autopkg-https/) script, and then tested all changed recipes manually to ensure exit codes of recipe run remains the same before/after the change.
Thanks for considering!
_This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso) v1.2.0._
> Update all available URLs from HTTP to HTTPS
